export const ACHIEVEMENTS = [
  { id: 0, category: "재력", icon: "💰", title: "풋내기", desc: "15,000골드 벌기.", guide: "초반 작물 재배와 낚시를 꾸준히 하면 달성 가능합니다." },
  { id: 1, category: "재력", icon: "💰", title: "소몰이", desc: "50,000골드 벌기.", guide: "가공품을 팔면 수익이 크게 증가합니다." },
  { id: 2, category: "재력", icon: "💰", title: "농가 주인", desc: "250,000골드 벌기.", guide: "다수확 작물을 대량 재배하세요." },
  { id: 3, category: "재력", icon: "💰", title: "백만장자", desc: "1,000,000골드 벌기.", guide: "고대 과일이나 스타후르츠를 온실에서 기르고 와인으로 가공하세요." },
  { id: 4, category: "재력", icon: "💰", title: "전설", desc: "10,000,000골드 벌기 (히든 업적).", guide: "진저 섬 농장 활용, 지하실 숙성 와인이 핵심입니다." },
  { id: 5, category: "수집", icon: "🏆", title: "완성된 컬렉션", desc: "박물관 소장품 모두 완성.", guide: "정동석을 깨서 모든 유물/광물을 기부하세요." },
  { id: 6, category: "우정", icon: "❤️", title: "새 친구", desc: "주민 한 명과 친밀도 5 하트 달성.", guide: "주민이 사랑하는 선물을 생일날 주면 빠릅니다." },
  { id: 7, category: "우정", icon: "❤️", title: "절친", desc: "주민 한 명과 친밀도 10 하트 달성.", guide: "결혼 가능 NPC는 하트 8개 이후 부케를 주어야 합니다." },
  { id: 9, category: "우정", icon: "❤️", title: "총애 받는 농부", desc: "주민 8명과 친밀도 10 하트 달성.", guide: "루아우 축제에서 최고 스프를 만들거나 선물을 꾸준히 돌리세요." },
  { id: 11, category: "우정", icon: "❤️", title: "무리", desc: "주민 4명과 친밀도 5 하트 달성.", guide: "자주 만나는 사람들을 위주로 선물을 주세요." },
  { id: 12, category: "우정", icon: "❤️", title: "인맥 형성", desc: "주민 10명과 친밀도 5 하트 달성.", guide: "여관에 저녁마다 방문해 선물을 돌리세요." },
  { id: 13, category: "우정", icon: "❤️", title: "인기인", desc: "주민 20명과 친밀도 5 하트 달성.", guide: "매주 주어지는 2회의 선물 횟수를 꽉꽉 채우세요." },
  { id: 15, category: "요리", icon: "🍳", title: "요리사", desc: "10가지 요리 만들기.", guide: "집을 업그레이드하고 소스 여왕에서 레시피를 배우세요." },
  { id: 16, category: "요리", icon: "🍳", title: "수셰프", desc: "25가지 요리 만들기.", guide: "이웃과 친해지면 요리 레시피를 많이 보내줍니다." },
  { id: 17, category: "요리", icon: "🍳", title: "미식가 셰프", desc: "모든 요리 만들기.", guide: "냉장고를 여러 개 만들어 재료를 비축해두세요." },
  { id: 18, category: "제작 및 업그레이드", icon: "🛠", title: "출세", desc: "집 업그레이드하기.", guide: "목재 450개와 10,000G를 모아 로빈에게 가세요." },
  { id: 19, category: "제작 및 업그레이드", icon: "🛠", title: "크게 살기", desc: "집 최대 크기로 업그레이드하기.", guide: "단단한 나무 150개와 50,000G가 필요합니다." },
  { id: 20, category: "제작 및 업그레이드", icon: "🛠", title: "수작업", desc: "15가지 아이템 제작하기.", guide: "돌, 나무 등을 쓰는 기본 레시피 위주로 만드세요." },
  { id: 21, category: "제작 및 업그레이드", icon: "🛠", title: "장인", desc: "30가지 아이템 제작하기.", guide: "레벨업 보상이나 상인들에게서 도면을 사서 채울 수 있습니다." },
  { id: 22, category: "제작 및 업그레이드", icon: "🛠", title: "제작의 달인", desc: "모든 아이템 제작하기.", guide: "상점의 레시피를 빠짐없이 구매해야 합니다." },
  { id: 24, category: "낚시", icon: "🐟", title: "낚시꾼", desc: "10가지 물고기 잡기.", guide: "바다, 강, 호수에서 계절별 물고기를 낚아보세요." },
  { id: 25, category: "낚시", icon: "🐟", title: "경험 많은 뱃사람", desc: "24가지 물고기 잡기.", guide: "비 오는 날에만 나오는 물고기가 있으니 일기예보를 확인하세요." },
  { id: 26, category: "낚시", icon: "🐟", title: "낚시의 달인", desc: "모든 종류의 물고기 잡기.", guide: "전설의 물고기와 야시장, 사막 물고기가 포함됩니다." },
  { id: 27, category: "낚시", icon: "🐟", title: "낚시의 신", desc: "물고기 100마리 잡기.", guide: "종류와 상관없이 100마리를 낚으면 됩니다." },
  { id: 28, category: "수집", icon: "🏆", title: "보물창고", desc: "박물관에 40가지 다른 아이템 기증하기.", guide: "클린트에게 정동석을 모두 까면 쉽습니다." },
  { id: 29, category: "심부름", icon: "📋", title: "심부름꾼", desc: "'도움 필요함' 요청 10개 완수.", guide: "피에르 상점 앞 게시판 퀘스트를 완료하세요." },
  { id: 30, category: "심부름", icon: "📋", title: "큰 도움", desc: "'도움 필요함' 요청 40개 완수.", guide: "보상이 적더라도 꾸준히 받아서 완료하는 것이 포인트입니다." },
  { id: 31, category: "수집", icon: "🏆", title: "혼합 양식", desc: "각 작물을 15개씩 배송.", guide: "컬렉션 탭을 확인하며 계절마다 빼먹는 작물이 없게 유의하세요." },
  { id: 32, category: "수집", icon: "🏆", title: "단일재배", desc: "한 종류의 작물을 300개 배송.", guide: "다수확 작물을 한 계절 재배하면 순식간에 끝납니다." },
  { id: 33, category: "수집", icon: "🏆", title: "수송품 한가득", desc: "모든 아이템 운송하기.", guide: "컬렉션 창의 배송란을 모두 채워야 합니다." },
  { id: 23, category: "모험", icon: "⚔️", title: "The Bottom", desc: "광산 최하층에 도달.", guide: "120층까지 내려가 해골 열쇠를 얻으세요." },
  { id: 34, category: "기타", icon: "✨", title: "Prairie King", desc: "'대초원의 왕의 모험'에서 승리.", guide: "주점 아케이드 게임입니다." },
  { id: 101, category: "스토리", icon: "📖", title: "Local Legend", desc: "펠리컨 타운 마을 회관 완성.", guide: "모든 번들을 완성하세요." },
  { id: 102, category: "기타", icon: "✨", title: "Joja Co. Member Of The Year", desc: "조자 지역 개발 프로젝트 전부 완성.", guide: "조자 루트를 타서 돈으로 시설들을 개방하면 됩니다." },
  { id: 103, category: "기타", icon: "✨", title: "Mystery Of The Stardrops", desc: "모든 별방울 획득.", guide: "총 7개의 획득처를 모두 클리어해야 합니다." },
  { id: 104, category: "기타", icon: "✨", title: "Full House", desc: "결혼해서 두 명의 아이 낳기.", guide: "집을 업그레이드하고 배우자와 관계를 유지하세요." },
  { id: 105, category: "스킬", icon: "⭐", title: "Singular Talent", desc: "스킬 레벨 10 달성.", guide: "농사나 채집이 가장 빠르게 10레벨에 도달합니다." },
  { id: 106, category: "스킬", icon: "⭐", title: "Master Of The Five Ways", desc: "모든 스킬 레벨 10 달성.", guide: "농사, 채광, 채집, 낚시, 전투 모두 만렙을 찍으세요." },
  { id: 107, category: "모험", icon: "⚔️", title: "Protector Of The Valley", desc: "모험가의 길드의 몬스터 토벌 목표 전부 완료.", guide: "길드 게시판에 적힌 마릿수만큼 사냥하세요." },
  { id: 108, category: "기타", icon: "✨", title: "Fector's Challenge", desc: "'대초원의 왕의 모험'을 죽지 않고 클리어. (히든 업적)", guide: "1.5버전 이후 이어하기 꼼수가 가능합니다." },
  { id: 40, category: "기타", icon: "✨", title: "먼 곳의 해안", desc: "진저 섬에 도달.", guide: "마을 회관 완성 후 윌리의 배를 수리하세요." },
  { id: 35, category: "기타", icon: "✨", title: "독서왕", desc: "모든 책 읽기. 참고: 능력 책에만 적용됩니다.", guide: "1.6 업데이트. 발굴 등을 통해 숨겨진 19종의 책을 읽으세요." },
  { id: 36, category: "기타", icon: "✨", title: "최고의 평점", desc: "영화 보기.", guide: "버려진 조자 마트를 영화관으로 바꾼 후 방문하세요." },
  { id: 37, category: "기타", icon: "✨", title: "블루 리본", desc: "스타듀 밸리 품평회 농가 전시 우승하기.", guide: "가을 16일 품평회에 고등급의 다양한 종류 아이템 9개를 전시하세요." },
  { id: 38, category: "우정", icon: "❤️", title: "잊을 수 없는 스프", desc: "도지사를 기쁘게 하기.", guide: "루아우 축제 스프에 최고급 재료를 넣으세요." },
  { id: 39, category: "심부름", icon: "📋", title: "좋은 이웃", desc: "숲의 이웃이 가정을 꾸릴 수 있게 돕기.", guide: "거대한 그루터기 퀘스트 라인을 완료하세요." },
  { id: 41, category: "모험", icon: "⚔️", title: "깊은 곳의 위험", desc: "'위험한' 광산 바닥에 도달.", guide: "치(Qi)의 특수 퀘스트 중 하나인 '위험한 광산' 120층을 정복하세요." },
  { id: 42, category: "모험", icon: "⚔️", title: "무한한 힘", desc: "가장 강한 무기 획득.", guide: "진저 섬 화산 대장간에서 갤럭시 소울을 합성하세요." },
  { id: 44, category: "기타", icon: "✨", title: "완벽", desc: "정상에 도달.", guide: "완벽함 추적기를 100% 채운 후 정상에 오르세요." }
];
